name: CI
on: [push, pull_request]

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir test-output
          echo hello > test-output/hello.txt
          echo world > test-output/world.txt
          echo 'console.log("hi")' > test-output/hi.js
      - uses: ./upload
        with:
          name: hello-2-test-output
          path: test-output
          github-token: ${{ secrets.GITHUB_TOKEN }}
  vitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: |
          npm install vitest @vitest/ui --save-dev
          echo 'export const add = (a: number, b: number) => a + b' >> calc.ts
          echo 'export const addBad = (a: number, b: number) => a + b + Math.random()' >> calc.ts
          echo 'export const sub = (a: number, b: number) => a - b' >> calc.ts
          mkdir test
          echo 'import {test, expect} from "vitest"' >> test/adding.test.ts
          echo 'import {add, addBad} from "../calc"' >> test/adding.test.ts
          echo 'test("add well", () => expect(add(1, 1)).toEqual(2))' >> test/adding.test.ts
          echo 'test("add badly", () => expect(addBad(1, 1)).toEqual(2))' >> test/adding.test.ts
      - name: run tests
        run: npx vitest --reporter html || echo 'failed'
      - uses: ./upload
        with:
          name: vitest
          path: html
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: |
          npm install @playwright/test --save-dev
          echo 'export const add = (a: number, b: number) => a + b' >> calc.ts
          echo 'export const addBad = (a: number, b: number) => a + b + Math.random()' >> calc.ts
          echo 'export const sub = (a: number, b: number) => a - b' >> calc.ts
          mkdir test
          echo 'import {test, expect} from "@playwright/test"' >> test/adding.test.ts
          echo 'import * as calc from "../calc"' >> test/adding.test.ts
          echo 'test("add well", () => expect(calc.add(1, 1)).toEqual(2))' >> test/adding.test.ts
          echo 'test("add badly", () => expect(calc.addBad(1, 1)).toEqual(2))' >> test/adding.test.ts
      - name: run tests
        run: npx playwright test --reporter html || echo failed
      - uses: ./upload
        with:
          name: playwright
          path: playwright-report
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p website
      - name: setup
        working-directory: ./website
        run: |
          git clone https://github.com/shuding/nextra-docs-template
          cd nextra-docs-template
          echo 'module.exports = withNextra({
            images: {unoptimized: true},
            output: "export",
            basePath: "/artifact/${{github.repository}}/${{github.run_id}}/website"
          })' >> next.config.js
          npm install
      - name: build site
        run: npm run build
        working-directory: website/nextra-docs-template
      - uses: ./upload
        with:
          name: website
          path: website/nextra-docs-template/out
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: |
          npm install eslint eslint-plugin-mmkal @eslint/config-inspector --save-dev
          echo "module.exports = require('eslint-plugin-mmkal').recommendedFlatConfigs" >> eslint.config.js
      - name: inspect eslint config
        run: npx @eslint/config-inspector build
      - uses: ./upload
        with:
          name: eslint
          path: .eslint-config-inspector
  ava:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p ava/test
      - name: setup
        run: |
          echo 'const {add, addBad} = require("../calc")' >> test/adding.test.js
          echo 'test("add well", () => expect(add(1, 1)).toEqual(2))' >> test/adding.test.js
          echo 'test("add badly", () => expect(addBad(1, 1)).toEqual(2))' >> test/adding.test.js
          echo 'test("bad snapshot", () => expect({foo: addBad(1, 1)}).toMatchInlineSnapshot(`{"foo": 2}`))' >> test/snaps.test.js
        working-directory: ./ava
      - name: run tests
        run: npm test || echo 'failed'
      - uses: ./upload
        with:
          name: ava
          path: ./ava/results.xml
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: |
          echo '
          def add(a, b):
            return a + b
          def addBad(a, b):
            return a + b + random.random()
          def sub(a, b):
            return a - b

          def test_add_well():
            assert add(1, 1) == 2
          def test_add_badly():
            assert addBad(1, 1) == 2
          ' >> test.py
          pip install pytest
          pip install pytest-html
      - name: run tests
        run: pytest test.py --html report/index.html || echo failed
      - uses: ./upload
        with:
          name: pytest
          path: report
  mocha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: |
          npm install mocha --save-dev
          echo 'exports.add = (a, b) => a + b' >> calc.js
          echo 'exports.addBad = (a, b) => a + b + Math.random()' >> calc.js
          echo 'exports.sub = (a, b) => a - b' >> calc.js
          mkdir test
          echo 'const assert = require("assert")' >> test/adding.test.js
          echo 'const {add, addBad} = require("../calc")' >> test/adding.test.js
          echo 'it("adds well", () => assert.strictEqual(add(1, 1), 2))' >> test/adding.test.js
          echo 'it("adds badly", () => assert.strictEqual(addBad(1, 1), 2))' >> test/adding.test.js
      - run: npx mocha --reporter doc > output.html || echo 'failed'
      - uses: ./upload
        if: always()
        with:
            name: mocha
            path: output.html
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup
        # https://go.dev/doc/tutorial/add-a-test
        run: |
          go mod init example.com/greetings
          go get github.com/vakenbolt/go-test-report
          go install github.com/vakenbolt/go-test-report

          echo 'package greetings

          import "math/rand"

          func Hello(name string) string {
              return "Hi, " + name + ". Welcome!"
          }

          func HelloBad(name string) string {
              return "Hi, " + name + ". Welcome!" + string(rune(rand.Intn(26) + 65))
          }' > greetings.go

          echo 'package greetings

          import ("testing")

          func TestGreetsWell(t *testing.T) {
              actual := Hello("Gladys")
              expected := "Hi, Gladys. Welcome!"
              if actual != expected {
                  t.Errorf("Result was incorrect, got: %s, want: %s.", actual, expected)
              }
          }

          func TestGreetsBadly(t *testing.T) {
              actual := HelloBad("Gladys")
              expected := "Hi, Gladys. Welcome!"
              if actual == expected {
                  t.Errorf("Result was unexpectedly correct, got: %s", actual)
              }
          }' > greetings_test.go
      - run: ls ~/go/bin
      - name: run tests
        run: go test -json | ~/go/bin/go-test-report || echo 'failed'
      - uses: ./upload
        with:
          name: go
          path: test_report.html
